### ISSUE TITLE
eclipse.ini file has unparseble option and uses unexpected variable

### ISSUE THREAD

**Issue by bbaassssiiee** [AlbanAndrieu/ansible-eclipse#3]
The double-dash for Xmx does not parse, and I would expect use of {{ eclipse_Xmx }}
- name:  eclipse | Configure eclipse ini configuration (Xmx)
  lineinfile: regexp="^-Xmx512m" line="--Xmx{{ eclipse_XXMaxPermSize }}" dest={{eclipse_base_dir}}/eclipse-{{eclipse_major}}/eclipse.ini
  when: eclipse_ini_enabled
##

**Comment by AlbanAndrieu** [comment]
Feel free to contribute by creating a pull request

**Comment by bbaassssiiee** [comment]
https://github.com/AlbanAndrieu/ansible-eclipse/pull/4 was merged
