### ISSUE TITLE
Dockerfile and build.sh in repo

### ISSUE THREAD

**Issue by Eothred** [AlbanAndrieu/ansible-eclipse#8]
By default docker_files_enable is set to yes, which means the Dockerfile and build.sh are overwritten by using the templates (at least for me). Should they still be tracked in the repository then? Alternatively one could set the docker_files_enable to no by default?
##

**Comment by AlbanAndrieu** [comment]
docker_files_enable is set to false by default in default/main.yml
It is overrided in the eclipse.yml used by travis.
I am not to understand your request, you can eventually create a PR to better explain me

**Comment by Eothred** [comment]
Aaah, sorry I have been using eclipse.yml rather than the default/main.yml, which is the reason behind the confusion.
My issue is invalid then.
